---

# Path that holds a workspace for each {{ adept_job }}
# must be coordinated with adept yaml instruction files
kommandir_workspaces: /mnt/workspaces

# Name of disk device to back {{ kommandir_workspaces }}
kommandir_volumedev: /dev/vdb

# Partition number on disk device to create
kommandir_volumeprt: 1
