---

docker_autotest:
    test_image:
        host: "registry.access.redhat.com"
        user: "rhel7"
        name: "rhel"
        tag: "latest"
        build_url:
    preserve_fqins:
        - "registry.access.redhat.com/rhel7/rhel:latest"
    preserve_cnames: []
    execute: true
    enable_bugzilla: true
