---

# Depends:
#   adept_path
#   peon_metadata
# Registers:
#   touchstone_touched

- name: touchstone_touched flag is set True
  set_fact:
    touchstone_touched: True

- name: host_vars directory exists
  file:
    path: '{{ adept_path }}/host_vars'
    state: directory
  delegate_to: localhost

- name: touchstone_touched persists in host_vars/inventory_hostname
  lineinfile:
    create: true
    dest: '{{ adept_path}}/host_vars/{{ inventory_hostname }}.yml'
    regexp: 'touchstone_touched.*'
    line: 'touchstone_touched: True'
  delegate_to: localhost
