---

# Depends:
#   destdir: directory where openrc.sh file to be rendered
#   auth_url: openstack auth url
#   tenant_name:
#   username:
#   password

- name: openstack openrc.sh file is deployed to workspace
  template:
    src: roles/openstack/templates/openrc.sh.j2
    dest: "{{ destdir }}/openrc.sh"
    mode: 0770
