---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

# N/B: Must set force_handlers: True in play to make sure handlers
# are called to release lock even if the play fails.

- name: FIXME
  debug:
    msg: 'Acquire/block on an {{ lock_type | default("exclusive") }} lock, across all running jobs on exekutir.  Needed to protect against multiple kommandir creations / installs / destruction at same time.'
  register: result
  # Pretend like nothing changed if lock_release is false (not the default)
  changed_when: lock_release | default(True) # and result | changed
  notify:
    - "Release lock on exekutir"
  delegate_to: exekutir
  # This could block for the duration of another job's setup/cleanup/run
  # (not supported for debug module)
  #async: "{{ 60 * 60 }}"
  #poll: 10
