---

# Maximum time to wait (in seconds) for each git operation to complete
git_op_timeout: '{{ 60 * 30 }}'

# Interval time (in seconds) to wait between each git status check
git_op_status_delay: '10'

# List of dictionaries, with options to the git ansible module.
# However, instead of `dest`, specify cache-dir relative path in `cachepath`
git_cache_args: {}

# When true, always force-clone, clobbering any posible local changes.
always_force: False
