---

- name: System is  unsubscribed
  redhat_subscription:
  args:
    username: "{{ rhsm.username }}"
    password: "{{ rhsm.password }}"
    state: absent
  register: result
  until: result | success
  retries: "{{ rhsm_retries }}"
  delay: "{{ rhsm_delay }}"
