---

# Depends:
#   is_atomic
#   ostree_remote:
#       name
#       spec
#       url
#       extra
# Registers:
#   rpms_updated: boolean
#   needs_reboot: boolean

- fail:
    msg: "Attempt to apply the atomic_upgrade role onto a non-Atomic host"
  when: not is_atomic

- name: remote already exists
  command: ostree remote list
  register: remote_list

- name: ostree command is executed
  command: >
    /usr/bin/ostree remote
                    add
                    {{ ostree_remote.extra | default('') }}
                    {{ ostree_remote.name }}
                    {{ ostree_remote.url }}
  when: not (remote_list.stdout | search(ostree_remote.name))

- name: current deployment origin refspec is known
  shell: >
    ostree admin status |
    grep -A 2 '^\*' |
    grep 'origin refspec: ' |
    cut -d: -f2 |
    tr -d [:blank:]
  register: ostree_status

- name: rebase to alternate remote
  command: rpm-ostree rebase '{{ ostree_remote.name }}:{{ ostree_remote.spec }}'
  register: atomic_rebase
  changed_when: atomic_rebase.stdout | search('to start a reboot')
  when: ostree_status.stdout != ostree_remote.name

- name: set flag when changes require reboot
  set_fact:
    needs_reboot: True
    rpms_updated: True
  when: atomic_rebase is defined and atomic_rebase | changed

- name: set flag false when changes not made
  set_fact:
    rpms_updated: False
  when: atomic_rebase is undefined
