---

# Depends:
#   - kommandir_workspace
#   - kommandir_sync_excludes
#   - adept_path
#   - no_log_synchronize

- name: kommandir workspace adept path excluded temporarily
  set_fact:
    _kwape:
        - "--exclude=adept/***"

- name: kommandir workspace transfered to controller host
  synchronize:
    mode: pull
    compress: True
    dest: '{{ workspace }}/'
    links: True
    perms: True
    recursive: True
    # When contents differ, prefer remote content over local
    checksum: True
    # Copy contents to dest, not src directory itself
    src: '{{ kommandir_workspace }}/'
    rsync_opts: '{{ kommandir_sync_excludes |
                    union(_kwape) }}'
  no_log: '{{ no_log_synchronize | default(true) }}'

- name: kommandir adept transfered to controller host
  synchronize:
    mode: pull
    compress: True
    dest: '{{ adept_path }}/'
    links: True
    perms: True
    recursive: True
    # When contents differ, prefer remote content over local
    checksum: True
    src: '{{ kommandir_workspace }}/adept/'
    rsync_opts: '{{ kommandir_sync_excludes }}'
  no_log: '{{ no_log_synchronize | default(true) }}'

- name: Giblets in kommandir's workspace are removed during cleanup
  file:
    path: "{{ kommandir_workspace }}/{{ item }}"
    state: absent
  when: 'adept_context == "cleanup"'
  ignore_errors: True  # Don't fail play on missing item
  # No reason to leave these around to soak up diskspace
  with_items:
    - "adept"
    - "cache"
    - "dockertest"
