---

- hosts: peons:&subscribed:&{{ adept_job }}
  roles:
    - subscribed

- hosts: peons:&partitioned:&{{ adept_job }}
  roles:
    - partitioned

- hosts: peons:&rebooted:&{{ adept_job }}
  roles:
    - rebooted

- hosts: peons:&yumrepos:&{{ adept_job }}
  roles:
    - yumrepos

# TODO: Apply all/most roles by conditional instead
#       of group-membership.  Similar to below.
- hosts: peons:&{{ adept_job }}
  roles:
    - role: lvm
      when: lvg_ops is defined or lvol_ops is defined

    - role: swap_enabled
      when: swap_device is defined

- hosts: peons:&installed:&{{ adept_job }}
  roles:
    - installed

- hosts: peons:&updated:&{{ adept_job }}
  roles:
    - updated

- hosts: peons:&atomic_upgrade:&{{ adept_job }}
  roles:
    - atomic_upgrade

- hosts: peons:rebooted:&{{ adept_job }}
  roles:
    - rebooted

- hosts: peons:&{{ adept_job }}
  roles:
    - peon
    - role: docker-storage-setup
      when: sysconfig_dss_lines != [] or sysconfig_dss_template != ""
    - services

- hosts: peons:rebooted:&{{ adept_job }}
  roles:
    - rebooted
