---

- hosts: subscribed
  gather_facts: post_rhr_gather
  roles:
    - subscribed

- hosts: rhel
  gather_facts: post_rhr_gather
  roles:
    - rhel

- hosts: rhelah
  gather_facts: post_rhr_gather
  roles:
    - rhelah

- hosts: centos
  gather_facts: post_rhr_gather
  roles:
    - centos

- hosts: fedora
  gather_facts: post_rhr_gather
  roles:
    - fedora

- hosts: all
  gather_facts: post_rhr_gather
  roles:
    - { role: rebooted, when: needs_reboot }
