---

- hosts: exekutir
  # Assume inventory is incomplete (kommandir is unreachable)
  gather_facts: False
  # Guarantee immediate non-zero exit, do not continue w/ other hosts
  any_errors_fatal: true
  pre_tasks:
    - name: Gather exekutir facts exclusive of other inventory hosts
      setup:
  roles:
    - common
    - ansible_versioned
    - compatible_ansible
    - exekutir_workspace_setup
    - role: inventory_updated
      inventory_hostnames:
        - exekutir

- hosts: kommandir
  # Inventory may still be incomplete
  gather_facts: False
  # Ensure exclusive lock is released, even on role failure
  force_handlers: True
  # Guarantee immediate non-zero exit, do not continue w/ other hosts
  any_errors_fatal: true
  roles:
    - common
    - role: exekutir_lock
      lock_type: "exclusive"
    - kommandir_discovered
    - role: inventory_updated
      inventory_hostnames:
        - kommandir
        - exekutir
    - kommandir_up
    - role: kommandir_installed
      when: "'nocloud' not in hostvars.kommandir.group_names"
    - role: kommandir_setup
      when: "'nocloud' not in hostvars.kommandir.group_names"
  # Exclusive lock is released by handler

- hosts: kommandir
  # Guarantee immediate non-zero exit, do not continue w/ other hosts
  any_errors_fatal: true
  roles:
    - common
    - role: exekutir_lock
      lock_type: "shared"
      lock_release: False
    # One-time setup, then synchronizes from exekutir -> kommandir
    - kommandir_workspace_setup
    # In case job.xn fails, local copy matches remote
    - kommandir_to_exekutir_sync
  # Shared lock is maintained
