---

- name: kmndrip file path is buffered when variable undefined
  set_fact:
    kmndrip_path: '{{ workspace }}/KMNDRIP'

- name: kmndrip value is buffered from file when undefined
  set_fact:
    kmndrip: '{{ lookup("file", kmndrip_path) }}'

# Older ansible needs the path this way
- include: ../../../roles/common/tasks/update_inventory.yml
  vars:
    # These come from task(s) above
    update_hostname: '{{ kmndrname }}'
    update_ip: '{{ kmndrip }}'
    update_groups:
        - sync_out
        - kommandir
        - sync_back
    update_extra: 'ansible_user=root ansible_ssh_user=root ansible_become=false'
