---

# N/B: Must be compatible with older ansible versions,
# since this play actually sets up a controlled version of ansible

- include: setup.yml
  when: adept_context == 'setup'

- include: run.yml
  when: adept_context == 'run'

- include: cleanup.yml
  when: adept_context == 'cleanup'
