---

# Depends:
#   hostvars_destination

- name: System's hostvars written to hostvars_destination (ansible < 2.2)
  delegate_to: localhost
  copy:
    dest: "{{ hostvars_destination }}"
    content: "{{ hostvars[inventory_hostname] | to_nice_yaml }}"
  when: ansible_version.string | version_compare("2.2", "<")

- name: System's hostvars written to hostvars_destination (ansible >= 2.2)
  delegate_to: localhost
  copy:
    dest: "{{ hostvars_destination }}"
    content: "{{ hostvars[inventory_hostname] | to_nice_yaml(indent=4) }}"
  when: ansible_version.string | version_compare("2.2", ">=")
