---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

# Any environment variables needed for cloud_provisioning_command
cloud_environment: {}
