---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

# Verify all inputs/state is ready for cloud_discovery_command
cloud_environment: {}
