---

# Depends:
#   - ignore_errors: (optional) boolean
#   - adept_path
#   - workspace

- name: openstack dynamic inventory cache is flushed
  shell: "{{ workspace }}/inventory/openstack.py --list --refresh &> /dev/null"
  ignore_errors: '{{ ignore_errors | default(False, True) }}'
