---

# many contexts require this to function
- block:

    - name: openstack configuration is deployed to worksapce
      template:
       src: clouds.yml.j2
       dest: "{{ workspace }}/clouds.yml"

    - name: openstack configuration directory exists
      file:
        path: '/etc/openstack'
        state: directory

    - include: roles/openstack/tasks/openrcsh.yml
      vars:
        destdir: '{{ workspace }}'
        auth_url: '{{ adept_openstack.clouds.default.auth.auth_url }}'
        tenant_name: '{{ adept_openstack.clouds.default.auth.tenant_name }}'
        username: '{{ adept_openstack.clouds.default.auth.username }}'
        password: '{{ adept_openstack.clouds.default.auth.password }}'

    - name: openstack configuration is linked from worksapce
      file:
        force: True
        path: "/etc/openstack/clouds.yml"
        src: "{{ workspace }}/clouds.yml"
        state: link

    - name: openstack dynamic inventory script is deployed
      copy:
        src: openstack.py
        dest: "{{ workspace }}/inventory/"
        follow: True
        mode: 0775
      register: openstack_py

    # Make sure current state is always updated
    - include: roles/openstack/tasks/cache_flush.yml
      when: openstack_py | changed

  rescue:
    # inventory will choke on next run if this exists
    - file:
        path: "{{ workspace }}/inventory/openstack.py"
        state: absent
    - fail:
        msg: "Openstack dynamic inventory failing, check credentials/settings"
