---

# Depends:
#   - peon
#   - _peon_facts
# Registers:
#   - _peon_facts

- debug:
    msg: "Working on peon: {{ peon.uuid }}"

- name: peon is in status active
  os_server_facts:
    cloud: default
    server: '{{ peon.uuid }}'
    wait: False
  # defines openstack_servers
  until: openstack_servers[0].status == "ACTIVE"
  retries: 600
  delay: 1

- name: peon facts are buffered
  set_fact:
    _peon_facts: |
        {{ _peon_facts |
            combine({
                openstack_servers[0].human_id: openstack_servers[0]
                    }) }}

- name: peons ssh port is listening
  wait_for:
    port: 22
    host: '{{ openstack_servers[0].public_v4 }}'
    connect_timeout: 1
    delay: 10
    state: started
    timeout: 120
  delegate_to: localhost

- name: in-memory inventory is updated with peon by name
  add_host:
    name: '{{ peon.uuid }}'
    groups: '{{ peon.groups | join(",") }}'
  args:
    ansible_host: '{{ openstack_servers[0].public_v4 }}'
