---

# All contexts require this to function
- include: roles/openstack/tasks/config.yml

# Both of these load from cache if present
- include: roles/peon/tasks/peons.yml
- include: roles/openstack/tasks/service_catalog.yml

- include: roles/openstack/tasks/setup.yml
  when: adept_context == 'setup'

- include: roles/openstack/tasks/run.yml
  when: adept_context == 'run'

- include: roles/openstack/tasks/cleanup.yml
  when: adept_context == 'cleanup'
