---

# Depends:
#   - /etc/openstack/clouds.yml
# Registers:
#   - service_catalog: Written to $WORSKAPCE/service_catalog.yml
#                      if it doesn't already exist

- include: roles/common/tasks/chkfile.yml
  vars:
    filename: "service_catalog.yml"

- name: service_catalog is loaded from service_catalog.yml
  set_fact:
    service_catalog: '{{ lookup("file", filepath) | from_yaml }}'
  when: exists

- block:

    # Defines service_catalog + exits block
    - name: auth token is retrieved
      # uses /etc/openstack/clouds.yml
      os_auth:
        cloud: default

  when: service_catalog is undefined

# flag is needed that doesn't depend on _service_catalog_yml.stat.exists
- name: service_catalog is stored locally
  copy:
    content: "{{ service_catalog | to_nice_yaml }}"
    dest: "{{ filepath }}"
  when: not exists
