---

- name: docker services are stopped
  service:
    name: "{{ item }}"
    state: stopped
  # There is no docker-latest on fedora
  when: 'is_enterprise or item != "docker-latest"'
  with_items:
    - "docker"
    - "docker-latest"

- name: Copy systemd unit files for customization
  copy:
    remote_src: True
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename() }}"
  when: 'is_enterprise or not item | search("latest")'
  with_fileglob:
    - "/usr/lib/systemd/system/docker*.service"

- name: The MountFlags=slave option is not present in customized unit files
  replace:
    dest: "{{ item }}"
    regexp: 'MountFlags=slave'
    replace: ''
  with_fileglob:
    - "/usr/lib/systemd/system/docker*.service"

- name: Systemd is reloaded
  command: systemctl daemon-reload
