---

- name: docker/docker-latest services are stopped
  service:
    name: "{{ item }}"
    state: stopped
  # There is no docker-latest on fedora
  when: 'is_enterprise or item != "docker-latest"'
  with_items:
    - "docker"
    - "docker-latest"

- name: The docker/docker-latest systemd unit config. drop-directory exists
  file:
    path: "/etc/systemd/system/{{ item }}.service.d"
    state: directory
  when: 'is_enterprise or item != "docker-latest"'
  with_items:
    - "docker"
    - "docker-latest"

- name: The docker/docker-latest config. drop-file is marked ansible-managed
  blockinfile:
    dest: "/etc/systemd/system/{{ item }}.service.d/liverestore.conf"
    create: True
  when: 'is_enterprise or item != "docker-latest"'
  with_items:
    - "docker"
    - "docker-latest"

- name: docker/docker-latest config. drop-file's MountFlags option is cleared
  ini_file:
    dest: "/etc/systemd/system/{{ item }}.service.d/liverestore.conf"
    section: "Service"
    option: "MountFlags"
    value: ""
  when: 'is_enterprise or item != "docker-latest"'
  with_items:
    - "docker"
    - "docker-latest"

- name: docker/docker-latest config. drop-file's KillMode option is set
  ini_file:
    dest: "/etc/systemd/system/{{ item }}.service.d/liverestore.conf"
    section: "Service"
    option: "KillMode"
    value: "process"
  when: 'is_enterprise or item != "docker-latest"'
  with_items:
    - "docker"
    - "docker-latest"

- name: Systemd is reloaded
  command: systemctl daemon-reload
