---

- name: slave ansible facts written out to workspace
  copy:
    dest: "{{ workspace }}/{{ inventory_hostname }}_{{ adept_context }}_facts.yml"
    content: "{{ hostvars[inventory_hostname] | to_nice_yaml }}"

- include: roles/common/tasks/failif_lt.yml
  vars:
    lhs_version: "{{ ansible_version.full }}"
    rhs_version: "2.1"

- include: roles/slave/tasks/setup.yml
  when: adept_context == 'setup'

- name: slave is member of group from adept_cloud_type variable
  include: roles/common/tasks/update_inventory.yml
  vars:
    update_hostname: 'localhost'
    update_ip: '127.0.0.1'
    update_extra: 'ansible_become=false ansible_connection=local'
    update_groups:
        - "{{ adept_cloud_type }}"

- include: roles/slave/tasks/run.yml
  when: adept_context == 'run'

- include: roles/slave/tasks/cleanup.yml
  when: adept_context == 'cleanup'
