---

# Additional userdata needed to switch atomic-host peons to use docker-latest
# must be defined here, as it may be referenced from top-level variables.yml file
# passed in by adept.py
docker_latest_userdata:
    write_files:
        - path: /etc/sysconfig/docker
          content: |
            OPTIONS="--selinux-enabled --log-driver=journald"
            ADD_REGISTRY="--add-registry registry.access.redhat.com"
            DOCKERBINARY=/usr/bin/docker-latest
    bootcmd:
        - cloud-init-per once instance systemctl disable docker
        - cloud-init-per once instance systemctl enable docker-latest

