---

# Depends:
#   peon.uuid
# Registers:
#   result

- name: The sleep command runs successfuly on peon
  raw: /bin/sleep 1s
  ignore_errors: True
  register: result
  until: result | success
  retries: 6
  delay: 10
