---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

- assert:
    that:
        - "compatible_ansible_minimum | default() in empty or ansible_version.string | version_compare(compatible_ansible_minimum, '>=')"
        - "compatible_ansible_maximum | default() in empty or ansible_version.string | version_compare(compatible_ansible_maximum, '<')"
