---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

- assert:
    that:
        - "compatible_ansible_maximum is defined"
        - "compatible_ansible_minimum is defined"
        - "compatible_ansible_minimum in [None,'',[],{}] or ansible_version.string | version_compare(compatible_ansible_minimum, '>=')"
        - "compatible_ansible_maximum in [None,'',[],{}] or ansible_version.string | version_compare(compatible_ansible_maximum, '<')"
