---

# Flag set True to reboot the host
needs_reboot: False

# Time to wait for ssh port to close
shutdown_timeout: 30

# Maximum time to wait for system to become available again (in seconds)
bootup_timeout: 300
