---

- assert:
    that:
        - 'autotest_docker_path is defined'

- name: Key variables are displayed
  debug:
    var: "{{ item }}"
  when: adept_debug
  with_items: ["autotest_docker_path", "docker_autotest_timeout"]

- name: Control timeout set in terms of seconds
  lineinfile:
    backrefs: true
    dest: "{{ autotest_docker_path }}/control"
    follow: True
    line: "\\1 {{ docker_autotest_timeout }} * 60"
    regexp: "^(TIMEOUT\\s*=\\s*).*$"
  when: docker_autotest_timeout is defined
