---

- assert:
    that:
      - 'empty is defined'
      - 'autotest_docker_path is defined'
      - 'autotest_dest_dir is defined'

- include: parse_prd.yml
  when: pull_request_description | default() not in empty

- block:

    - name: Execute Docker autotest
      shell: >
        $AUTOTEST_PATH/client/autotest-local
        {{ autotest_docker_path }}/control
        {{ '--args="$MMARGS"'
           if docker_autotest_mmargs | default() not in empty
           else '' }}
        &> /dev/null
      environment:
        AUTOTEST_PATH: "{{ autotest_dest_dir }}"
        # Mitigate some risk of accepting external input for executing
        # inside cloud.  The rest is done by heavily filtering the input
        MMARGS: "{{ docker_autotest_mmargs }}"
      args:
        chdir: "{{ autotest_docker_path }}"
      register: autotest_execution
      async: "{{ (docker_autotest_timeout | default(240)) * 61 }}"
      poll: 60
      # Any Autotest failures will eventually be reflected as missing results
      ignore_errors: True

  always:

    # All tasks ignore_errors
    - include: produce_results.yml

    # All tasks ignore_errors
    - include: collect_results.yml

  when: docker_autotest.execute
