---

- hosts: kommandir
  vars_files:
      - kommandir_vars.yml
  # If any of these fail, they will prevent creation of file (below)
  # which will be detected by test_exekutir_xn.sh
  pre_tasks:
    - assert:
        that:
            - 'uuid == "something_i_made_up_for_ci"'
            - 'repo_rpms is undefined'
            - 'enable_repos is undefined'
            - 'disable_repos is undefined'
            - 'install_rpms is undefined'
            - 'git_cache_args is undefined'
            - 'some_magic_variable_for_testing == "value_for_magic_variable"'
            - 'adept_context in ["setup", "run", "cleanup"]'
  roles:
    - common
  post_tasks:
    - set_fact:
        result: "This is the {{ job_name }} job's test play, running on kommandir for the {{ adept_context }} context"
    - debug:
        msg: "{{ result }}"
    # Contents of these files varified in test_exekutir_xn.sh
    - lineinfile:
        dest: "{{ workspace }}/results/test_file_from_{{ adept_context }}.txt"
        create: true
        insertafter: EOF
        line: "{{ result }}"
