---

- assert:
    that:
        - 'empty is defined'
        - 'disk_device | default() not in empty'
        - 'parted_opts | default() not in empty'
        # No parted on Atomic, bail out
        - 'is_atomic != True'

- name: State of /root/<disk_device>_partitioned file is known
  stat:
    path: "/root/{{ disk_device | basename }}_partitioned"
  register: result

- name: Key variables are displayed
  debug:
    var: "{{ item }}"
  with_items: ["result", "disk_device","parted_opts"]
  when: adept_debug

- block:

    - name: Partition table is updated
      parted:
        align: '{{ parted_opts.align | default(omit) }}'
        device: '{{ disk_device }}'
        flags: '{{ parted_opts.flags | default(omit) }}'
        label: '{{ parted_opts.label | default(omit) }}'
        name: '{{ parted_opts.name | default(omit) }}'
        number: '{{ parted_opts.number | default(omit) }}'
        part_end: '{{ parted_opts.part_end | default(omit) }}'
        part_start: '{{ parted_opts.part_start | default(omit) }}'
        part_type: '{{ parted_opts.part_type | default(omit) }}'
        state: '{{ parted_opts.state | default(omit) }}'
        unit: '{{ parted_opts.unit | default(omit) }}'

    - name: system needs reboot when partition table changed
      set_fact:
        needs_reboot: True

  always:

    - name: Drop /root/<disk_device>_partitioned file to avoid re-partitioning on accident
      file:
        path: "/root/{{ disk_device | basename }}_partitioned"
        state: touch

  when: result.stat is undefined or
        not result.stat.exists | bool
