---

peon_groups:
    - openstack
    - fedora
    - updated
    - docker
    - autotested

peon_image: 'Fedora-Cloud-26'

peon_size: '20'

peon_flavor: 'm1.medium'

peon_userdata: '{{ workspace }}/roles/peon_created/files/nodocker_userdata.yml'
