---


# N/B: This file may be overwritten when job_path is syncd to
# kommandir's kommandir_workspace
compatible_ansible_minimum: "2.3"

# This is always localhost.  The details below will be re-added by
# kommandir_workspace_setup role if it's missing.
ansible_connection: local
ansible_become: false
ansible_host: localhost
ansible_ssh_host: "{{ ansible_host }}"
ansible_shell_type: sh
