---

peon_groups:
    - "{{ hostvars.kommandir.peon_cloud_group | mandatory }}"
    - rhel
    - subscribed
    - updated
    - docker-latest
    - overlay2
    - autotested

peon_image: 'rhel-7.4-server-x86_64-latest'
