---

# Format Ref: https://docs.ansible.com/ansible/devel/plugins/inventory/yaml.html

all:
    hosts:
        rhel-latest:
            peon_groups:
                # Allows switching clouds.  Default: peon_cloud_group=openstack
                - "{{ hostvars.kommandir.peon_cloud_group | mandatory }}"
                # Generic OS group, interacts with cloud_group (above)
                - rhel
                # OS Specialization group, interacts with topic group (below)
                - latest_rhel
                # Topic-group, the main purpose for the job
                - autotested

    children:
        # Group of hosts which are to be provisioned/managed by ADEPT
        peons:
            hosts:
                rhel-latest

        # OS Specialization group
        latest_rhel:
            vars:
                # No subscription necessary, "latest" cooked into image
                rhsm: {}
                # OpenStack *-latest images include 'compose.repo', use that.
                disable_all_rh_repos: True  # subscription-manager repos
                # 'compose.repo' doesn't include extras, use the latest
                yum_repos:
                    - '{{ _private_latest_base_yum_repo | default({}) }}'
                    - '{{ _private_latest_optional_yum_repo | default({}) }}'
                    - '{{ _private_latest_extras_yum_repo | default({}) }}'
                enable_repos:
                    - '{{ "base"
                          if _private_latest_base_yum_repo is defined
                          else "" }}'  # can't use `omit` here.
                    - '{{ "optional"
                          if _private_latest_optional_yum_repo is defined
                          else "" }}'
                    - '{{ "latest-extras"
                          if _private_latest_extras_yum_repo is defined
                          else "" }}'

                # Low-level rpms to install
                install_rpms:
                    - bridge-utils
                    - bzip2
                    - cloud-utils-growpart
                    - findutils
                    - gdb
                    - git
                    - glibc-devel
                    - iputils
                    - libselinux-python
                    - nfs-utils
                    - procps
                    - selinux-policy-targeted
                    - tar
                    - which

        # Topic-group
        autotested:
            vars:
                # No mail sent when empty
                notification_email: '{{ _private_notification_email | default("") }}'
                notification_url: '{{ _private_notification_url | default("") }}'
                autotest_rpm_deps:
                    - atomic
                    - docker
                    - docker-latest
                    - docker-selinux
                    - runc
