---

lvol_ops:
    - lv: swap
      size: 512
      state: present
      vg: atomicos
      opts: '--zero y --wipesignatures y'

    - lv: root
      vg: atomicos
      size: 5g
      opts: '--zero y --wipesignatures y'

post_cmnds:
    - "/usr/sbin/xfs_growfs /"

swap_device: /dev/atomicos/swap
