---

- include: roles/peon/tasks/setup.yml
  when: adept_context == 'setup'

- include: roles/peon/tasks/run.yml
  when: adept_context == 'run'

- include: roles/peon/tasks/cleanup.yml
  when: adept_context == 'cleanup'
