---

# Depends:
#   - _peon
#   - inner_item
#   - adept_job
# Registers:
#   - _peon_set

- name: peon's ansible groups are buffered
  set_fact:
    _groups: "{{ _peon.groups }}"

- name: peon's dynamic job-specific group is set
  set_fact:
    _groups: '{{ _groups | union([adept_job]) }}'

- name: peon's group list is updated from buffer
  set_fact:
    _peon: '{{ _peon | combine({"groups": _groups}) }}'

- name: peon version forced to be a string
  set_fact:
    _peon: '{{ _peon | combine({"version": _peon.version | string}) }}'

- name: peon shorter-uuid is generated
  set_fact:
    _uuid: "{{
                _peon.name
            }}-{{
                _peon.version | trim
            }}-{{
                adept_job
            }}-{{
                _peon | to_uuid |
                regex_replace('(\\w+-){4}(\\w+)', '\\2')
            }}"

- name: peon uuid is also valid dns name
  set_fact:
    _uuid: "{{ _uuid | trim | regex_replace('[^-a-zA-Z0-9]', '-') }}"

- name: peon uuid is set
  set_fact:
    _peon: '{{ _peon | combine({"uuid": _uuid}) }}'

- name: peon is stored in buffer
  set_fact:
    _peon_set: "{{ (_peon_set + [_peon]) | unique }}"
