---

# depends:
#   - dirpath (default: workspace)
#   - filename
# registers:
#   - result
#   - filepath
#   - exists

- name: full path to file is formed
  set_fact:
    filepath: "{{ dirpath | default(workspace) }}/{{ filename }}"

- debug:
    msg: "Checking for existance of {{ filepath }}"

- name: status of file is retrieved
  stat:
    path: '{{ filepath }}'
  register: result

- name: file does not exist by default
  set_fact:
    exists: False

- name: file exists if status indicates regular file
  set_fact:
    exists: True
  when: result.stat.exists is defined and
        result.stat.exists and
        result.stat.isreg is defined and
        result.stat.isreg
