---

# Dependencies:
#   - lhs_version: Version number to check
#   - rhs_version: Required minimum version

- name: rhs version is greater or equal to lhs version
  fail:
    msg: "{{ lhs_version }} < {{ rhs_version }}"
  when: '{{ lhs_version | version_compare(rhs_version, "<") }}'
