---

# Depends:
#   repo_list: list of repos to enable
# Registers
#   repo_csv: CSV list of repos to enable

- name: done flag is set false
  set_fact:
    _done: False

- name: repo list converted to csv
  set_fact:
    repo_csv: '{{ repo_list | list | join(",") }}'
    _done: True
  when: repo_list is defined and repo_list != None and
        repo_list != [] and repo_list != ""

- name: repo list set empty
  set_fact:
    repo_csv: ""
    _done: True
  when: not _done
