---

# Depends:
#   switch_ansible_user_to: defaults to root
# Registers:
#   unbecomed: True/False, I know it's bad english

- name: ansible_user switch is set when required
  set_fact:
    unbecomed: True
  when: ansible_user != 'root' and ansible_become

- name: ansible_user switch defaults to false
  set_fact:
    unbecomed: False
  when: switch_ssh_user is undefined

- block:

    - name: switch_ansible_user_to defaults to root
      set_fact:
        switch_ansible_user_to: "{{ switch_ansible_user_to | default('root') }}"

    - name: new ansible_user home directory is known
      getent:
        database: passewd
        key: "{{ switch_ansible_user_to }}"

    - name: new ansible_user account ssh access copied
      copy:
        dest: "{{ getent_passwd[5] }}/.ssh"
        directory_mode: 0700
        follow: True
        group: "{{ switch_ansible_user_to }}"
        owner: "{{ switch_ansible_user_to }}"
        mode: 0600
        remote_src: True
        src: "{{ ansible_user_dir }}/.ssh/authorized_keys"

    - include: roles/common/tasks/update_inventory.yml
      vars:
        update_hostname: "{{ inventory_hostname }}"
        update_ip: "{{ ansible_host }}"
        update_groups: "{{ group_names }}"
        update_extra: "ansible_user={{ switch_ansible_user_to }} become={{ switch_ansible_user_to != 'root' }}"

    - name: working ansible_user account is switched in
      set_fact:
        ansible_user: "{{ switch_ansible_user_to }}"
        ansible_become: "{{ switch_ansible_user_to != 'root' }}"
        ansible_user_dir: "{{ getent_passwd[5] }}"
        ansible_user_id: "{{ switch_ansible_user_to }}"
        ansible_user_gid: "{{ getent_passwd[3] }}"
        ansible_user_uid: "{{ getent_passwd[2] }}"
        ansible_user_shell: "{{ getent_passwd[6] }}"

  when: unbecomed
