---

# List of dictionaries containing ansible git-module options.
# cachepath is the path relative to {{ workspace }}/cache directory.
git_cache_args:
    - repo: "https://github.com/autotest/autotest.git"
      recursive: False
      cachepath: 'autotest'
    - repo: "https://github.com/autotest/autotest-docker.git"
      recursive: True
      cachepath: 'autotest-docker'
    - repo: "https://github.com/python-bugzilla/python-bugzilla.git"
      recursive: False
      cachepath: "python-bugzilla"
      version: "v1.2.2"
