---

enable_repos:
    - base
    - extras

repo_rpms:
    - epel-release

install_rpms:
    - docker
    - docker-latest
    - runc
    - oci-umount
    - atomic
    - docker-selinux
    - procps
    - tar
    - lvm2
    - findutils
    - bzip2
    - gdb
    - bridge-utils
    - nfs-utils
    - git
    - glibc-devel
    - which
    - cloud-utils-growpart
    - selinux-policy-targeted
    - libselinux-python
    - iputils
