---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

# These are all default values for this host, any may be overridden
# on the ansible command-line

# You probably don't want to change any of these
ansible_connection: "local"
ansible_become: false
ansible_host: "localhost"
ansible_ssh_host: "{{ ansible_host }}"
compatible_ansible_minimum: "2.1"

# Directory where kommandir's workspace will be sync'd to/from
kommandir_workspace: '{{ workspace }}/kommandir_workspace'

# Path where job's kommandir.xn, inventory, and kommandir_vars are found.
# N/B: Intended to be overriden from command-line or in exekutir_vars.yml
job_path: "{{ lookup('env','ADEPT_PATH') }}/jobs/full"

# Short name of the job, used to identify/mark resources and files
# N/B: Intended to be overriden from command-line or in exekutir_vars.yml
job_name: "{{ job_path | basename }}"

# Prevents resource clashes across jobs, must be unique,
# must be DNS and User Name compatible.  Must be all on
# a single line, b/c common role will hard-code the actual value.
# N/B: Intended to be overriden from command-line or in exekutir_vars.yml with
# more human-readable value.
uuid: "x{{ [ansible_date_time, ansible_hostname,
            ansible_uptime_seconds, ansible_memfree_mb] |
           to_uuid |
           replace('-','') |
           truncate(8,true,'') }}"
