---

# Depends:
#   failure_component
#   failure_message
# Registers:
#   result

- block:

    - name: Current local date is captured
      command: date +%F
      # Recycle shared, temporary variable name
      register: result
      delegate_to: localhost

    - name: Date is buffered as ansible_date_time
      set_fact:
        ansible_date_time:
            date: "{{ result.stdout }}"

  when: ansible_date_time is undefined

- name: Results sub-directory is defined
  set_fact:
    result: "{{ workspace }}/results/{{ inventory_hostname }}"

- name: Results sub-directory exists
  file:
  args:
    path: "{{ result }}"
    state: directory
  delegate_to: localhost

- name: Peons begin with cooked failure results.junit file
  template:
    src: "roles/autotested/templates/cooked_results.junit.j2"
    dest: "{{ result }}/results.junit"
  delegate_to: localhost
