---

# Depends:
#   - no_log_synchronize
#   - ...others....

# N/B: Running inside block's "always" task list, everything must pass

- name: Results sub-directory is defined
  set_fact:
    result: "{{ workspace }}/results/{{ inventory_hostname }}"

- name: Ensure results sub-directory exists
  file:
  args:
    path: "{{ result }}"
    state: directory
  ignore_errors: true
  delegate_to: localhost

- name: Collect autotest results
  synchronize:
    mode: pull
    src: "{{ autotest_dest_dir }}/client/results/default/"
    dest: "{{ result }}"
  ignore_errors: true
  no_log: '{{ no_log_synchronize | default(true) }}'

- name: Collect Docker Autotest customized config
  synchronize:
    # The test VM is the SOURCE, and local system is destination
    mode: pull
    src: "{{ autotest_docker_path }}/config_custom"
    dest: "{{ result }}"
  ignore_errors: true
  no_log: '{{ no_log_synchronize | default(true) }}'
