---

- name: DOCKERBINARY is uncommented
  replace:
    backup: True
    dest: /etc/sysconfig/docker
    regexp: "^\\s*#\\s*(DOCKERBINARY=.*)"
    replace: "\\1"
  when: sysconfig_docker_latest | default(False)

- name: DOCKERBINARY commented out
  replace:
    backup: True
    dest: /etc/sysconfig/docker
    regexp: "^\\s*(DOCKERBINARY=.*)"
    replace: "# \\1"
  when: not (sysconfig_docker_latest | default(False))
