---

- assert:
    that:
        - '"subscribed" in group_names'

- name: System is  unsubscribed
  shell: subscription-manager unregister | true
  register: result
  ignore_errors: True

- name: Result is displayed when adept_debug
  debug:
    var: "result"
  when: adept_debug
