---
# So nginx can serve files. We can't seem to do this using the
# ansible file module with setype: it's not recursive.
- name: autotest | SELinux policy 1
  action: file path={{destdir}}/client/results state=directory

# Sigh. On RHEL, semanage fcontext -a can be run over and over again.
# On Fedora, the second time, it barfs:
#    ValueError: File context for [...] already defined
# Let's try using the sefcontext module instead
- name: autotest | SELinux policy 2 | ansible prerequisites
  package: name=policycoreutils-python state=present

- name: autotest | SELinux policy 2
  sefcontext: target="{{destdir}}/client/results(/.*)?"
              setype=httpd_sys_content_t

- name: autotest | SELinux policy 3
  command: restorecon -R {{destdir}}/client/results

- name: nginx is installed
  package: name=nginx state=present

- name: configure nginx | root
  lineinfile: dest=/etc/nginx/nginx.conf
              regexp="^\s+root\s"
              state=absent
  notify: restart nginx

- name: configure nginx | default
  action: copy src=files/nginx-default.conf
              dest=/etc/nginx/default.d/default.conf
              owner=root group=root
  notify: restart nginx

- name: open http port
  firewalld: port=80/tcp state=enabled permanent=true immediate=true
