---

- name: docker-latest related items in /etc/sysconfig/docker are un-commented
  replace:
    backup: True
    dest: /etc/sysconfig/docker
    regexp: "^\\s*#\\s*({{ item }}=.+)"
    replace: "\\1"
  when: sysconfig_docker_latest | default(False)
  with_items:
    - 'DOCKERBINARY'
    - 'DOCKERDBINARY'
    - 'DOCKER_CONTAINERD_BINARY'
    - 'DOCKER_CONTAINERD_SHIM_BINARY'

- block:

    - name: docker-latest related items in /etc/sysconfig/docker are commented-out
      replace:
        backup: True
        dest: /etc/sysconfig/docker
        regexp: "^\\s*({{ item }}=.+)"
        replace: "# COMMENTED BY ADEPT's sysconfig_docker role: \\1"
      when: not (sysconfig_docker_latest | default(False))
      with_items:
        - 'DOCKERBINARY'
        - 'DOCKERDBINARY'
        - 'DOCKER_CONTAINERD_BINARY'
        - 'DOCKER_CONTAINERD_SHIM_BINARY'

    - name: OpenStack MTU workaround is enabled for docker and docker-latest
      lineinfile:
        dest: "/etc/sysconfig/{{ item }}"
        backrefs: True
        # Grab quoting characters, then match only if mtu option NOT present
        regexp: >
            ^OPTIONS=(['"])(((?!--mtu=1400).)*)(['"])$
        line: >
            OPTIONS=\1\2 --mtu=1400\4
        create: True  # don't fail play if file doesn't exist (broken in some ansible versions)
      when: ansible_distribution_version | version_compare('7.4', 'lt')
      with_items:
        - "docker"
        - "docker-latest"

  when: ansible_distribution_version | version_compare('7.5', 'lt')
