---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

- debug:
    msg: "Joining {{ inventory_hostname }} to {{ dynamic_groups }}"
  when: dynamic_groups != []

- name: buffer list of existing groups (minus 'ungrouped')
  set_fact:
    result: '{{ group_names | difference(["ungrouped"]) }}'

- name: host dynamicly added to listed groups
  add_host:
    name: "{{ inventory_hostname }}"
    groups: "{{
                dynamic_groups | join(',')
             }}{% if result != [] %},{{
                result | join(',') }}{% endif %}"
  # set in defaults
  when: dynamic_groups != []
