---

- name: docker services are stopped
  service:
    name: "{{ item }}"
    state: stopped
  # There is no docker-latest on fedora
  when: 'is_enterprise or item != "docker-latest"'
  with_items:
    - "docker"
    - "docker-latest"

- name: Add lines to sysconfig/d-s-s
  lineinfile:
    create: true
    backup: False
    dest: "/etc/sysconfig/docker-storage-setup"
    line: "{{ item }}"
  with_items: '{{ sysconfig_dss_lines }}'

- name: Add lines to sysconfig/d-s-s latest
  lineinfile:
    create: true
    backup: False
    dest: "/etc/sysconfig/docker-latest-storage-setup"
    line: "{{ item }}"
  with_items: '{{ sysconfig_dss_lines }}'

# Necessary so docker / docker-latest service properly runs d-s-s
- name: The /var/lib/docker and docker-latest directories are empty
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/lib/docker"
    - "/var/lib/docker-latest"
