---

all:
    hosts:
        rhel-latest:
            peon_groups:
                - "{{ hostvars.kommandir.peon_cloud_group | mandatory }}"
                - rhel
                - latest_rhel_copr
                - autotested

    children:
        peons:
            hosts:
                rhel-latest

        latest_rhel_copr:
            vars:
                rhsm: {}
                disable_all_rh_repos: True  # subscription-manager repos
                yum_repos:
                    - '{{ _private_latest_extras_yum_repo | default({}) }}'
                    - name: "baude-Upstream_CRIO_Family"
                      description: "Copr repo for Upstream_CRIO_Family owned by baude"
                      baseurl: "https://copr-be.cloud.fedoraproject.org/results/baude/Upstream_CRIO_Family/epel-7-x86_64/"
                      gpgkey: "https://copr-be.cloud.fedoraproject.org/results/baude/Upstream_CRIO_Family/pubkey.gpg"
                      gpgcheck: True

                enable_repos:
                    - base
                    - optional
                    - '{{ "latest-extras"
                          if _private_latest_extras_yum_repo is defined
                          else "optional" }}'  # can't use `omit` here.
                    - baude-Upstream_CRIO_Family
                install_rpms:
                    - bridge-utils
                    - bzip2
                    - cloud-utils-growpart
                    - findutils
                    - gdb
                    - git
                    - glibc-devel
                    - iputils
                    - libselinux-python
                    - nfs-utils
                    - procps
                    - selinux-policy-targeted
                    - tar
                    - which

        autotested:
            vars:
                # No mail sent when empty
                notification_email: '{{ _private_notification_email | default("") }}'
                notification_url: '{{ _private_notification_url | default("") }}'
