---

# Depends:
#   ansible_async_jobs
# Registers:
#   result
# Clears:
#   ansible_async_jobs

# Old ansible can't loop on includes for nesting loops,
# use a polled async task to busy-wait on any incomplete jobs
- include: async_poll.yml
  # ansible_async_jobs only defined when support is enabled
  with_items: '{{ ansible_async_jobs | default([]) }}'
  loop_control:
    loop_var: async_job

- name: ansible_async_jobs list is cleared
  set_fact:
    ansible_async_jobs: []
  # ansible_async_jobs only defined when support is enabled
  when: ansible_async_jobs is defined
