---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

cloud_type: 'nocloud'
