---

# Avoid needing to specify image names in every peon's host_vars
peon_image: >
  {#- RHEL Images -#}\
  {%-   if inventory_hostname|search("rhel7-2") -%}rhel-7.2-server-x86_64-released
  {%- elif inventory_hostname|search("rhel7-3") -%}rhel-7.3-server-x86_64-released
  {%- elif inventory_hostname|search("rhel7-4") -%}rhel-7.4-server-x86_64-released
  {%- elif inventory_hostname|search("rhel7-5") -%}rhel-7.5-server-x86_64-released
  {#- RHEL Fully-updated Images -#}\
  {%- elif inventory_hostname|search("rhel7-2-latest") -%}rhel-7.2-server-x86_64-latest
  {%- elif inventory_hostname|search("rhel7-3-latest") -%}rhel-7.3-server-x86_64-latest
  {%- elif inventory_hostname|search("rhel7-4-latest") -%}rhel-7.4-server-x86_64-latest
  {%- elif inventory_hostname|search("rhel7-5-latest") -%}rhel-7.5-server-x86_64-latest
  {%- elif inventory_hostname|search("rhel-latest") -%}rhel-7.6-server-x86_64-nightly
  {#- RHEL Atomic Host Images -#}\
  {%- elif inventory_hostname|search("rhelatomic7-2") -%}rhel-atomic-cloud-7.2-released-latest
  {%- elif inventory_hostname|search("rhelatomic7-3") -%}rhel-atomic-cloud-7.3-released-latest
  {%- elif inventory_hostname|search("rhelatomic7-4") -%}rhel-atomic-cloud-7.4-released-latest
  {%- elif inventory_hostname|search("rhelatomic7-5") -%}rhel-atomic-cloud-7.5-released-latest
  {%- elif inventory_hostname|search("rhelatomic-latest") -%}rhel-atomic-cloud-7.5-released-latest
  {#- Fedora Images -#}\
  {%- elif inventory_hostname|search("fedora26") -%}Fedora-Cloud-26
  {%- elif inventory_hostname|search("fedora27") -%}Fedora-Cloud-27
  {#- Fedora Atomic Host Images -#}\
  {%- elif inventory_hostname|search("fedoratomic26") -%}Fedora-Atomic-26
  {%- elif inventory_hostname|search("fedoratomic27") -%}Fedora-Atomic-27
  {#- CentOS 7 Images -#}\
  {%- elif inventory_hostname|search("centos7") -%}CentOS-Cloud-7
  {%- else -%}{{ 'Error: Peon not found while looking up image-name' | comment }}{%- endif -%}
