---

# Depends:
#   - lvg_ops: list of parameter dictionaries for lvg module
#   - lvol_ops: list of parameter dictionaries for lvol module
# Registers:
#   - result

- block:

    - command: /usr/sbin/lvm pvs
      changed_when: False
      register: result
    - debug:
        var: item
      with_items: '{{ result.stdout_lines }}'

    - command: /usr/sbin/lvm lvs
      changed_when: False
      register: result
    - debug:
        var: item
      with_items: '{{ result.stdout_lines }}'

    - command: /usr/sbin/lvm pvs
      changed_when: False
      register: result
    - debug:
        var: item
      with_items: '{{ result.stdout_lines }}'

  when: lvg_ops != [] or lvol_ops != []
