---

- assert:
    that:
        - 'empty is defined'
        - 'adept_context == "cleanup"'
        - 'cloud_destruction_command is defined'
        - 'inventory_hostname != "kommandir"'

- name: Key variables are displayed
  debug:
    var: "{{ item }}"
  with_items: ["adept_context","group_names","cloud_destruction_command.command"]
  when: adept_debug

- name: Destruction handlers notified
  command: '/bin/true'
  notify:
    - "peon destruction"
  changed_when: True
  delegate_to: kommandir
