---

# N/B: This file can be overwritten by a copy from job_path.

- hosts: kommandir
  # Can't assume all hosts are reachable
  gather_facts: False
  vars_files:
      - kommandir_vars.yml
  pre_tasks:
    - name: Gather kommandir facs exclusive of other inventory hosts
      setup:
        gather_subset: 'facter'
  roles:
    # Needed to group/add all peons
    - common

- hosts: peons
  gather_facts: False
  vars_files:
      - kommandir_vars.yml
  roles:
    - common
    - peon_common
    - role: unsubscribed
      when: cleanup and
            "subscribed" in group_names
    - role: peon_destroyed
      when: 'cleanup | default(True) and inventory_hostname != "kommandir"'

- hosts: kommandir
  # Can't assume all hosts are reachable
  gather_facts: False
  vars_files:
      - kommandir_vars.yml
  pre_tasks:
    - name: Gather kommandir facs exclusive of other inventory hosts
      setup:
        gather_subset: 'facter'
  roles:
    - workspace_cleanup
