---

# N/B: This file can be overwritten by a copy from job_path.

- hosts: peons
  strategy: linear  # The add_host module can only be run using linear strategy
  vars_files:
      - kommandir_vars.yml
  roles:
    - common
    - peon_common

      ##### Low-level roles only applied once, for speed and woopsie-avoidance
    - role: touchstone
      touch_touchstone: False


- hosts: peons
  # Outside of debug-mode, run all peons as fast as possible
  strategy: "{{ 'linear' if adept_debug | default(False) else 'free' }}"
  vars_files:
      - kommandir_vars.yml
  roles:
    - role: subscribed
      when: not stone_touched and
            rhsm is defined and
            "subscribed" in group_names and
            rhsm.username | default() not in empty and
            rhsm.password | default() not in empty

    - role: yumrepos
      when: not stone_touched

    - role: rawhide
      when: not stone_touched and
            'fedora' in group_names and 'rawhide' in group_names

    - role: atomic_rebase
      when: not stone_touched and
            is_atomic and
            ostree_remote | default() not in empty and
            ostree_remote.name | default() not in empty and
            ostree_remote.url | default() not in empty and
            ostree_remote.spec | default() not in empty

    - role: partitioned
      when: not stone_touched and
            disk_device | default() not in empty and
            parted_opts | default() not in empty

    - role: rebooted  # partitions or devices may have changed
      reboot_context: "beginning"  # failed_peon_result debugging help
      when: needs_reboot == True and
            not stone_touched

    - role: lvm
      when: not stone_touched and
            (lvg_ops | default() not in empty or
             lvol_ops | default() not in empty)

    - role: swap_enabled
      when: not stone_touched and
            swap_device | default() not in empty

    ##### End of low-level setup, indicate completion for any future runs
    - role: touchstone
      touch_touchstone: True


- hosts: peons
  # Outside of debug-mode, run all peons as fast as possible
  strategy: "{{ 'linear' if adept_debug | default(False) else 'free' }}"
  vars_files:
      - kommandir_vars.yml
  roles:
    - role: installed
      when: not is_atomic and
            install_rpms | default() not in empty

    - role: atomic_upgrade
      when: is_atomic and
            ostree_remote | default() in empty and
            'updated' in group_names

    - role: rebooted  # utilize any changed/updated software
      reboot_context: "middle"
      when: needs_reboot == True

    # Allow most/all prior tasks to run in permissive if necessary
    - role: selinux_enforcing  # Allow most/all prior tasks to run in permissive if necessary

    - services

    - role: rebooted  # Allow selinux to re-label if necessary
      reboot_context: "end"
      when: needs_reboot == True
