---

# N/B: This file can be overwritten by a copy from job_path.

- hosts: peons
  # Inventory is incomplete
  gather_facts: False
  vars_files:
      - kommandir_vars.yml
  roles:
    - common
    - role: peon_created
      when: ansible_host | default() not in empty and
            "recycled" not in group_names
    - role: peon_up
      reboot_context: "creation"
  post_tasks:
    - name: Some hosts may need ansible-dependencies installed before anything else happens.
      raw: "{{ item }}"  # raw commands don't require python
      args:
        executable: "/bin/bash"
      register: result
      with_items: '{{ peon_pre_raw_cmds | default([]) }}'
    - name: Peon's peon_pre_raw_cmds results are displayed
      debug:
          var: "item.stdout_lines"
      with_items: "{{ result.results }}"
      when: adept_debug
