---

# Depends:
#   ADEPT_PATH: environment variable
# Registers:
#   - adept_path: Either $ADEPT_PATH from environment or /var/lib/adept (default)

- name: The ADEPT_PATH env. var is loaded into adept_path variable
  set_fact:
    adept_path: '{{ lookup("env", "ADEPT_PATH") | default("/var/lib/adept", True) }}'
