---

# Depends:
# Registers:
#   - adept_optional: $ADEPT_OPTIONAL from environment if adept_optional is unset

- name: The ADEPT_OPTIONAL env. var is loaded into adept_optional if undefined
  set_fact:
    adept_optional: '{{ lookup("env", "ADEPT_OPTIONAL") }}'
  when: adept_optional is undefined
