---

# Registers:
#   is_enterprise

- name: The file /etc/redhat-release status is known
  stat:
    path: "/etc/redhat-release"
    follow: True
  register: exists

- name: The file exists and contains the word Enterprise
  set_fact:
    is_enterprise: True
  when: is_enterprise is undefined and
        exists.stat is defined and
        exists.stat.exists and
        exists.stat.isreg and
        lookup('pipe','head -1 /etc/redhat-release') | search('Enterprise')

- name: The file doesn't exist or contain the word Enterprise
  set_fact:
    is_enterprise: False
  when: is_enterprise is undefined
