---

# Depends:
#   - remove_hostname
#   - from_groups

- debug:
    msg: >
        Warning, it's not possible or sensible to update in-memory inventory
        .  Removal of {{ remove_hostname}} will take effect in next playbook
        execution, not this one!

- name: inventory groups are updated
  ini_file:
    dest: "{{ workspace }}/inventory/{{ group_name}}"
    no_extra_spaces: True
    section: "{{ group_name }}"
    # Must match how update_inventory.yml does it
    option: "{{ remove_hostname}} ansible_host"
    state: absent
  with_items: '{{ from_groups | list | difference(["all", "ungrouped"]) }}'
  loop_control:
    loop_var: group_name
