---

# Depends:
#   - update_hostname
#   - update_ip
#   - update_extra (optional)
#   - update_groups (list)

- name: Host entry is defined
  set_fact:
    # Old ansible needs ansible_ssh_host
    _host_entry: "{{ update_hostname }} ansible_host={{ update_ip }} ansible_ssh_host={{ update_ip }} {{ update_extra | default('') }}"

# Older ansible does includes differently :S
# TODO make this a role and add dependency?
- name: The WORKSPACE env. var is loaded into workspace variable
  set_fact:
    workspace: '{{ lookup("env", "WORKSPACE") | default("/var/lib/workspace") }}'

- name: inventory hosts are updated
  copy:
    dest: "{{ workspace }}/inventory/{{ update_hostname }}"
    content: '{{ _host_entry }}'

- name: inventory group files contains the group-names
  lineinfile:
    create: True
    dest: "{{ workspace }}/inventory/{{ item }}"
    line: "[{{ item }}]"
    state: present
    insertbefore: BOF
  when: item != None
  with_items: '{{ update_groups | default([]) }}'

- name: inventory groups files contain host entry
  lineinfile:
    dest: "{{ workspace }}/inventory/{{ item }}"
    regexp: "{{ update_hostname }}.*"
    line: '{{ update_hostname }}'
    state: present
  when: item != None
  with_items: '{{ update_groups | default([]) }}'

- name: runtime inventory is updated
  add_host: >
    name="{{ update_hostname }}"
    groups="{{ update_groups | list | join(',') }}"
    ansible_host="{{ update_ip }}"
    ansible_ssh_host="{{ update_ip }}"
    {{ update_extra | default('') | to_nice_json }}
