---

# Depends:
#   - swap_device

- block:

    - name: Run mkswap against swap_device
      command: mkswap "{{ swap_device }}"
      register: result
      ignore_errors: true

    - fail:
        msg: "Creating swap on {{ swap_device }} failed"
      # Don't fail if device is mounted - assume swap already setup
      when: result | failed and
            not result.stdout | search('is mounted')

    - name: Swap setup persists across reboots
      mount:
        fstype: swap
        name: "none"
        src: "{{ swap_device }}"
        passno: 0
        state: present
      when: result | success

    - name: All swap is enabled
      command: swapon -a
      when: result | success

  when: swap_device is defined and
        swap_device != ''
