---

################################################################
# N/B: This may be running on an old (2.1)  version of ansible #
################################################################

# It's assumed there will never be another application of setup
# or run contexts after cleanup.  The common role verifies this.
# Remove all unnecessary files/directories unless the adept_debug
# flag is set.

- assert:
    that:
        - 'inventory_hostname == "exekutir"'
        - 'workspace is defined'
        - 'kommandir_workspace is defined' 
        - 'not adept_debug'
        - 'job_xn_done'

- name: Unnecessary directories are removed from the exekutir's kommandir_workspace
  file:
    path: "{{ kommandir_workspace }}/{{ item }}"
    state: absent
  with_items:
    # Other files are preserved b/c they may have come from ouside the repo.
    # (i.e. some external job_path)
    - ".ansible"
    - ".ssh"
    - "adept.py"
    - "cache"

- name: Unnecessary directories are removed from the exekutir's workspace
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ inventory_dir }}"
    - "{{ workspace }}/.ansible"
    - "{{ workspace }}/.ssh"
    - "{{ workspace }}/group_vars"
    - "{{ workspace }}/host_vars"
    - "{{ workspace }}/cache"
    - "{{ workspace }}/roles"
    - "{{ workspace }}/kommandir.yml"
    - "{{ workspace }}/run.yml"
    - "{{ workspace }}/setup.yml"
    - "{{ workspace }}/cleanup.yml"
    - "{{ workspace }}/variables.yml"
